<?xml version="1.0"?>
<xsd:schema targetNamespace="http://www.n3r1.com/xmlschemas/RaceTrackExtensions/v1"
  elementFormDefault="qualified"
  xmlns="http://www.n3r1.com/xmlschemas/RaceTrackExtensions/v1"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation><xsd:documentation>
    This schema defines race track point-level extensions for GPX 1.1 files.
    The root element defined by this schema is intended to be used as a child
    of the "extensions" element of a GPX track point.
  </xsd:documentation></xsd:annotation>

  <xsd:element name="RaceTrackExtension" type="RaceTrackExtension_t" />

  <xsd:complexType name="RaceTrackExtension_t">
    <xsd:annotation><xsd:documentation>
      This type contains race track state metadata associated with a single
      track point.
    </xsd:documentation></xsd:annotation>
    <xsd:sequence>
      <xsd:element name="rtx_lap" type="Integer_t" minOccurs="0" />
      <xsd:element name="rtx_state" type="xsd:string" minOccurs="0" />
      <xsd:element name="rtx_lap_distance" type="Meters_t" minOccurs="0" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="Integer_t">
    <xsd:annotation><xsd:documentation>
      This type contains an integer value.
    </xsd:documentation></xsd:annotation>
    <xsd:restriction base="xsd:integer"/>
  </xsd:simpleType>

  <xsd:simpleType name="Meters_t">
    <xsd:annotation><xsd:documentation>
      This type contains a distance value measured in meters.
    </xsd:documentation></xsd:annotation>
    <xsd:restriction base="xsd:double"/>
  </xsd:simpleType>
</xsd:schema>
